### ISSUE TITLE
Upgrade project frontend to Svelte v5

### ISSUE THREAD

**Issue by ktenman** [ktenman/portfolio#17]
# Description
Our project currently uses an older version of the Svelte frontend framework. With the recent release of Svelte v5, we should evaluate upgrading to take advantage of the latest features, performance improvements, and long-term support.

This issue tracks the research and work required to upgrade our frontend codebase to Svelte v5.

## Tasks
- [ ] Research the changes and new features in Svelte v5
  - Review Svelte v5 release notes and changelog
  - Identify breaking changes that will require code modifications
  - List key new features that could benefit our project
- [ ] Assess the effort and impact of upgrading
  - Determine if any 3rd party libraries need to be updated for v5 compatibility
  - Spike upgrading a portion of the app to uncover any challenges
  - Estimate the total effort to upgrade the front fully
- [ ] Define a plan for incrementally upgrading to Svelte v5
  - Decide whether to do a big-bang upgrade or gradual migration
  - Break down the migration into discrete tasks 
  - Assign tasks to sprint(s) and team members
- [ ] Execute the upgrade
  - Create a feature branch for the upgrade work
  - Complete the upgrade tasks defined in the plan
  - Continuously run tests and manually test to identify any issues
  - Document any code changes and new Svelte v5 features leveraged
- [ ] Review, test and merge
  - Open a Pull Request for team review of the upgrade changes
  - Complete thorough regression testing of the frontend
  - Make any necessary fixes and get final approval
  - Merge to the main branch and deploy to staging/prod environments
- [ ] Update documentation and notify stakeholders
  - Update README and other relevant developer docs with Svelte v5 info
  - Announce the successful upgrade to the broader team and stakeholders

## Context
Keeping our frontend stack up-to-date is important for our application's long-term health and performance. By proactively upgrading to Svelte v5 soon after its release, we can take advantage of the latest capabilities and avoid falling behind.

This upgrade should be prioritized appropriately against other roadmap items, considering the effort required and potential benefits. The work should be thoughtfully planned out and tested to mitigate risk.

## References
- [Svelte v5 Announcement Blog Post](https://svelte.dev/blog/svelte-v5)
- [Svelte v5 Docs](https://svelte.dev/docs)
