### ISSUE TITLE
Improve SEO for Google

### ISSUE THREAD

**Issue by ktenman** [ktenman/portfolio#28]
## Current State
Our Vue.js application currently uses hash-based routing (`createWebHashHistory`). While this works well for single-page applications (SPAs), it's not optimal for search engine optimization (SEO) as search engines typically don't index content after the hash (#) in URLs.

## Problem
1. Hash-based routing limits our app's discoverability on search engines.
2. We lack proper meta tags and other SEO elements.
3. The app may not be easily crawlable by search engine bots.

### 1. Switch to HTML5 History Mode
Change the router to use `createWebHistory` instead of `createWebHashHistory`. This will require server-side configuration to handle routing properly.

```typescript
import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(),
  routes,
})
```

### 2. Implement Server-Side Rendering (SSR) or Static Site Generation (SSG)
Consider using Nuxt.js for Vue applications, which provides SSR out of the box, or investigate Vue's own SSR capabilities.

### 3. Add Meta Tags
Implement dynamic meta tags for each route to provide accurate descriptions and titles for different pages.

### 4. Create a Sitemap
Generate a sitemap.xml file to help search engines understand the structure of our site.

### 5. Implement Structured Data
Add structured data (JSON-LD) to provide more context about our content to search engines.

### 6. Optimize for Core Web Vitals
Ensure the app performs well in terms of loading speed, interactivity, and visual stability.

### 7. Implement proper Semantic HTML
Ensure we're using semantic HTML elements correctly throughout the app.

## Tasks
- [ ] Switch router to HTML5 History Mode
- [ ] Configure server to handle HTML5 History Mode routing
- [ ] Implement SSR or SSG (investigate Nuxt.js or Vue SSR)
- [ ] Add dynamic meta tags to routes
- [ ] Create and implement a sitemap.xml
- [ ] Add structured data (JSON-LD) for key pages
- [ ] Audit and optimize for Core Web Vitals
- [ ] Review and update HTML for better semantics

## Additional Considerations
- We may need to update our build and deployment processes to accommodate these changes.
- Testing will be crucial to ensure these changes don't break existing functionality.
- We should monitor our search rankings before and after these changes to measure their impact.

## Resources
- [Vue Router: HTML5 History Mode](https://router.vuejs.org/guide/essentials/history-mode.html)
- [Vue.js Server-Side Rendering Guide](https://vuejs.org/guide/scaling-up/ssr.html)
- [Google's SEO Starter Guide](https://developers.google.com/search/docs/fundamentals/seo-starter-guide)
- [Nuxt.js - Vue.js Framework](https://nuxtjs.org/)

Please review and provide feedback on these proposed changes. Once approved, we can break this down into smaller, actionable tasks.
