### ISSUE TITLE
 Add Swagger Documentation

### ISSUE THREAD

**Issue by ktenman** [ktenman/portfolio#29]
## Description
We need to add Swagger documentation to our API endpoints to improve the developer experience and make our API more accessible and understandable.

## Tasks
- [ ] Add Springdoc OpenAPI dependencies to the project
- [ ] Configure Swagger UI in the Spring Boot application
- [ ] Add OpenAPI annotations to all controller classes and methods
- [ ] Document request/response models using OpenAPI annotations
- [ ] Configure security schemes if applicable (e.g., JWT authentication)
- [ ] Test Swagger UI and ensure all endpoints are correctly documented
- [ ] Update README with information on how to access Swagger UI

## Implementation Details
1. Add the following dependency to `build.gradle.kts`:
   ```kotlin
   implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0")
   ```
2. Configure Swagger in `application.yml`:
   ```yaml
   springdoc:
     api-docs:
       path: /api-docs
     swagger-ui:
       path: /swagger-ui.html
   ```
3. Add `@Operation`, `@Parameter`, and other OpenAPI annotations to controllers
4. Use `@Schema` to document data models

## Acceptance Criteria
- Swagger UI is accessible at `/swagger-ui.html`
- All API endpoints are visible and properly documented in Swagger UI
- Request and response models are clearly described
- Authentication requirements (if any) are properly documented
- Developers can use Swagger UI to test API endpoints

## Additional Notes
- Consider using Swagger annotations to group endpoints logically
- Ensure sensitive information is not exposed in the documentation

## Estimated Time
4-6 hours
