### ISSUE TITLE
Refactor Long Methods in Services

### ISSUE THREAD

**Issue by ktenman** [ktenman/portfolio#31]
# Refactor Long Methods in Services

## Description
Some methods in our service classes, particularly in the `DailyPortfolioXirrJob`, are quite lengthy and complex. These methods should be refactored into smaller, more focused methods to improve our codebase's readability, maintainability, and testability.

## Background
Long methods can be difficult to understand, debug, and maintain. They often violate the Single Responsibility Principle, making unit testing more challenging. By breaking these methods down into smaller, more focused functions, we can improve the overall quality of our codebase.

## Objectives
- Improve code readability and maintainability
- Enhance the testability of individual components
- Reduce cognitive load when working with complex logic
- Adhere more closely to SOLID principles, particularly the Single Responsibility Principle

## Tasks
- [ ] Identify long methods in service classes (start with `DailyPortfolioXirrJob`)
- [ ] Analyze the identified methods to determine logical breakpoints
- [ ] Refactor long methods into smaller, more focused methods
- [ ] Ensure proper naming of new methods to convey their purpose clearly
- [ ] Update or add unit tests for the refactored methods
- [ ] Review and update any affected documentation
- [ ] Perform code review to ensure refactoring doesn't introduce new bugs
- [ ] Update any affected integration tests

## Implementation Details
Let's use the `DailyPortfolioXirrJob` as an example:

1. The `execute()` method could be broken down into smaller methods:

   ```kotlin
   class DailyPortfolioXirrJob {
     fun execute() {
       val transactions = getAllTransactions()
       val dateRange = calculateDateRange(transactions)
       val summaries = calculateSummaries(transactions, dateRange)
       saveSummaries(summaries)
     }

     private fun getAllTransactions(): List<PortfolioTransaction> {
       // Implementation
     }

     private fun calculateDateRange(transactions: List<PortfolioTransaction>): Pair<LocalDate, LocalDate> {
       // Implementation
     }

     private fun calculateSummaries(transactions: List<PortfolioTransaction>, dateRange: Pair<LocalDate, LocalDate>): List<PortfolioDailySummary> {
       // Implementation
     }

     private fun saveSummaries(summaries: List<PortfolioDailySummary>) {
       // Implementation
     }
   }
   ```

2. The `calculateSummaryForDate()` method could also be broken down:

   ```kotlin
   private fun calculateSummaryForDate(transactions: List<PortfolioTransaction>, date: LocalDate): PortfolioDailySummary {
     val (totalInvestment, currentValue) = processTransactions(transactions, date)
     val xirrResult = calculateXirr(transactions, currentValue, date)
     return createDailySummary(totalInvestment, currentValue, xirrResult, date)
   }

   private fun processTransactions(transactions: List<PortfolioTransaction>, date: LocalDate): Pair<BigDecimal, BigDecimal> {
     // Implementation
   }

   private fun calculateXirr(transactions: List<PortfolioTransaction>, currentValue: BigDecimal, date: LocalDate): Double {
     // Implementation
   }

   private fun createDailySummary(totalInvestment: BigDecimal, currentValue: BigDecimal, xirrResult: Double, date: LocalDate): PortfolioDailySummary {
     // Implementation
   }
   ```

## Acceptance Criteria
- Long methods in services are broken down into smaller, more focused methods
- Each method has a clear, single responsibility
- New methods are properly named to reflect their purpose
- Unit tests are updated or added to cover the new method structure
- Code readability is improved
- Overall functionality remains unchanged
- Performance is maintained or improved

## Estimated Time
10-15 hours

## Priority
Medium

## Additional Notes
- Consider using IntelliJ IDEA's refactoring tools to assist in the process
- This refactoring may reveal opportunities for further optimization or code reuse
- After refactoring, reassess the class structure. Some new methods might be better placed in separate, more specialized classes.

**Comment by ktenman** [comment]
This issue has been resolved through previous refactoring efforts.

**Current state of `DailyPortfolioXirrJob`:**
- Only 84 lines - acts as a thin orchestrator
- Delegates to specialized services (`TransactionService`, `SummaryService`, `CalculationService`)
- Uses coroutines for parallel processing
- Follows SOLID principles with clear single responsibility

**Related services are well-decomposed:**
- `SummaryService.kt` - 264 lines
- `CalculationService.kt` - 149 lines
- `InvestmentMetricsService.kt` - 330 lines

All acceptance criteria have been met through incremental improvements to the codebase.
